#!/bin/bash

# fail on errors
set -e
# be verbose
set -x

for OS in centos7 opensuse-42.2
do
	echo
	echo "Checking package build for ${OS} ...."
	echo
	buildlib/cbuild build-images ${OS}
	buildlib/cbuild pkg ${OS}
done
